### ISSUE TITLE
Unable to Spin Up Environment

### ISSUE THREAD

**Issue by ghost** [CircleCI-Public/macos-big-sur-preview-docs#3]
We have tested with the Big Sur executor but we had issues in “Spin Up Environment”.
 

> We timed out preparing a VM for this build, potentially due to our infrastructure or cloud provider.  Please retry the build in a few minutes
 

Also before the build started we had a warning
 

> This build could not be run with the selected resource class. The default Medium resource class was used to run this build. To use the resource class to speed up your build or avoid an out-of-memory error, you can upgrade to a Performance Plan.
 

Below is the exector we used in our yaml file.
 
 ```
 bigsur_ci_machine:
    resource_class: m2.medium
    macos:
      xcode: "110.12.4"
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
```
