### ISSUE TITLE
Ruby version mismatch?

### ISSUE THREAD

**Issue by gonzalonunez** [CircleCI-Public/macos-big-sur-preview-docs#4]
I just gave the new macOS Big Sur preview image a spin and I'm getting the following error with Ruby. Any help here would be greatly appreciated 🙂 

I was under the impression that [Ruby 2.7.2 was the correct version](https://circleci.com/docs/2.0/testing-ios/#images-using-xcode-117-and-later), should I remove this `step` and rely on the defaults?

### Error:

<img width="1000" alt="Screen Shot 2021-05-18 at 12 32 27 PM" src="https://user-images.githubusercontent.com/6403910/118712175-5102ff00-b7d5-11eb-8331-0d25f1fa258e.png">

### Gemfile:
```ruby
source "https://rubygems.org"
ruby "2.7.2"

gem "fastlane"
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```

### Config:
```yaml
defaults: &defaults
  macos:
    xcode: 12.5.0
  resource_class: m2.medium

  environment:
    FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
    FL_OUTPUT_DIR: output

version: 2.1
commands:
  # Workaround for Xcode 12 SSH issues
  # Bug fix: https://support.circleci.com/hc/en-us/articles/360044709573-Swift-Package-Manager-fails-to-clone-from-private-Git-repositories
  # Release notes: https://discuss.circleci.com/t/xcode-12-gm-released/37437
  xcode_12_ssh_fix:
    description: "Workaround for Xcode 12 SSH issues"
    steps:
      - run: sudo defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
      - run: rm ~/.ssh/id_rsa || true
      - run: for ip in $(dig @8.8.8.8 bitbucket.org +short); do ssh-keyscan bitbucket.org,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true

  set_ruby_version:
    description: "Sets the expected Ruby version"
    steps:
      - run:
          name: Set Ruby Version
          command: echo 'chruby ruby-2.7' >> ~/.bash_profile

  fastlane:
    description: "Runs the desired fastlane lane"
    parameters:
      lane:
        type: string
    steps:
      - run:
          name: Fastlane
          command: bundle exec fastlane << parameters.lane >>

  store_artifacts_and_results:
    description: "Stores all relevant results after an xcodebuild command"
    parameters:
      results_directory:
        type: string
    steps:
      - store_artifacts:
          path: ~/Library/Logs/DiagnosticReports
      - store_artifacts:
          path: <<parameters.results_directory>>
      - store_test_results:
          path: <<parameters.results_directory>>

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - xcode_12_ssh_fix
      - set_ruby_version
      - run: bundle install
      - fastlane:
          lane: "test"
      - store_artifacts_and_results:
          results_directory: "output"
      - store_artifacts:
          path: /tmp/__SnapshotArtifacts__    

  test_lib:
    <<: *defaults
    steps:
      - checkout
      - xcode_12_ssh_fix
      - set_ruby_version
      - run: bundle install
      - fastlane:
          lane: "test_lib"
      - store_artifacts_and_results:
          results_directory: "output"

workflows:
  version: 2
  test:
    jobs:
      - test
      - test_lib
```
